sonar.projectKey=ffreis-runner-comparison
sonar.organization=felipefuhr
sonar.sources=.
sonar.exclusions=tests/**
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml