name: DevOps / Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  labeler:
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-labeler.yml@v1.2.0
    with:
      rules-json: |-
        [
          {"label": "ci", "title": "/ci/i"},
          {"label": "infra", "title": "/infra/i"}
        ]
