name: DevOps / Scorecard

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  scorecard:
    permissions:
      id-token: write
      security-events: write
      contents: read
      actions: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-scorecard.yml@v1.2.0
    with:
      upload-sarif: true
