name: DevOps / Semantic PR

on:
  pull_request:

jobs:
  semantic-pr:
    permissions:
      pull-requests: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-semantic-pr.yml@v1.2.0
